name: my-first-workfolow
on: workflow_dispatch
jobs:
 first-jobs:
  runs-on: macos-13
  steps:
  - name: Say-hello
    run: echo "Hello Imtiaz"
  - name: Say-Bye
    run: echo "Bye Imtiaz and yusuf"
  - name: issues 
    run: echo "issue new"